# Generated by Django 4.1.3 on 2022-12-03 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_alter_usernft_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4)),
                ('reference_type', models.CharField(choices=[('POST', 'POST'), ('PROFILE_PIC', 'PROFILE_PIC')], db_index=True, max_length=20)),
                ('file_extension', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='users.user')),
            ],
        ),
    ]
