# Generated by Django 4.1.3 on 2022-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usernft',
            name='ticker',
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
    ]
