# Generated by Django 4.1.3 on 2022-12-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usernft_created_at_usernft_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernft',
            name='contract_address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernft',
            name='nft_creation_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='usernft',
            name='transaction_hash',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
